title: "Jean Fan | Personal site"
email: "jeanfan@jhu.edu"
description: Personal website of Prof. Jean Fan
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jean.fan" # the base hostname & protocol for your site, e.g. http://example.com
permalink: "/:year/:month/:day/:title:output_ext"
# Build settings
markdown: kramdown
theme: minima

# General Settings
logo_url: "/assets/img/logo/logo.png"
banner_url: "/assets/img/banner-small.jpg"

company_name: Jean Fan
company_url: "https://jean.fan"
lab_url: "https://jef.works"
twitter_url: "https://twitter.com/JEFworks"
instagram_url: "https://www.instagram.com/jefworks/"
youtube_url: "https://www.youtube.com/channel/UCFrwIRJvLGp631o9Bo_BtYw"
linkedin_url: "http://linkedin.com/in/jeanfan"

collections:
  home_one_services:
    output: true